default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: url-shortner

test:
  <<: *default
  database: url-shortner

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: url-shortner